name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Install Render CLI
      run: curl -fsSL https://cli.render.com/install | bash

    - name: Authenticate Render
      run: render login --api-key ${{ secrets.RENDER_API_KEY }}

    - name: Deploy to Render
      run: render deploy service ${{ secrets.RENDER_SERVICE_ID}}
